version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo-challenge
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo-challenge
    ports:
      - "3306:3306"
    networks:
      - my-net

  app:
    platform: linux/x86_64
    build:
      context: .
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USERNAME: demo
      DB_NAME: demo-challenge
      DB_PASSWORD: demo-challenge
      DB_HOST: db
      DB_PORT: 3306
    networks:
      - my-net

networks:
  my-net:
    # Use a custom driver
    driver: bridge