default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'demo' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'demo-challenge' } %>
  host: <%= ENV.fetch('DB_HOST') { '0.0.0.0' } %>
  port: <%= ENV.fetch('DB_PORT') { '3307' } %>

development:
  <<: *default
  database: 'demo-challenge'

test:
  <<: *default
  database: 'demo-challenge'

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'demo-challenge' }%>
